chore: update sp1 dep

diff --git a/scripts/find_clang b/scripts/find_clang
--- a/scripts/find_clang
+++ b/scripts/find_clang
@@ -2,4 +2,40 @@
 #
 # An utility script used to find a binary of clang 16+
 
-echo "clang"
+if [[ -n "${CLANG}" ]]; then
+  echo "${CLANG}"
+  exit 0
+fi
+
+# To cope with packaging messes from different distros, we would search
+# for a different binary other than clang, then convert it back to clang
+# at the end.
+SEARCH_TARGET="${SEARCH_TARGET:-llvm-strip}"
+
+CANDIDATES=("${SEARCH_TARGET}-19" "${SEARCH_TARGET}-20" "${SEARCH_TARGET}-21" "${SEARCH_TARGET}-22" "${SEARCH_TARGET}-23")
+
+BREW_PREFIX=$(brew --prefix 2> /dev/null)
+if [[ -n "${BREW_PREFIX}" ]]; then
+  CANDIDATES+=(
+    "${BREW_PREFIX}/opt/llvm@19/bin/${SEARCH_TARGET}"
+    "${BREW_PREFIX}/opt/llvm@20/bin/${SEARCH_TARGET}"
+    "${BREW_PREFIX}/opt/llvm@21/bin/${SEARCH_TARGET}"
+    "${BREW_PREFIX}/opt/llvm@22/bin/${SEARCH_TARGET}"
+    "${BREW_PREFIX}/opt/llvm@23/bin/${SEARCH_TARGET}"
+  )
+fi
+
+# make default clang last
+CANDIDATES+=("${SEARCH_TARGET}")
+
+for candidate in ${CANDIDATES[@]}; do
+  OUTPUT=$($candidate --version 2> /dev/null | grep 'version [0-9]' | head -n 1 | cut -d'.' -f 1 | grep -o '[0-9][0-9]*')
+
+  if [[ $((OUTPUT)) -ge 19 ]]; then
+    echo "${candidate/${SEARCH_TARGET}/clang}"
+    exit 0
+  fi
+done
+
+>&2 echo "Cannot find clang of version 19+!"
+exit 1
